### ISSUE TITLE
$.ajax is not a function

### ISSUE THREAD

**Issue by codiiv** [fengyuanchen/jquery-cropper#1]
Once I  get the base64 image string in the   main.js  file, the console throws   "$.ajax is not a function" error message. 

How do you actually initialize jQuery Ajax  post to server? The documentation is not clear

**Comment by codiiv** [comment]
I found out it was because the code included in demo is the jQuery light  version that precludes ajax. 
Replaced  `https://code.jquery.com/jquery-3.3.1.slim.min.js`  with  the full jQuery version   ( `https://code.jquery.com/jquery-3.3.1.min.js`  )  and that worked

**Comment by Albion99** [comment]
jemoeder werkt niet

**Comment by Albion99** [comment]
haha lol scrub noscope360 m8 lmao roflllll

**Comment by AjeshVyas** [comment]
> I found out it was because the code included in demo is the jQuery light version that precludes ajax.
> Replaced `https://code.jquery.com/jquery-3.3.1.slim.min.js` with the full jQuery version ( `https://code.jquery.com/jquery-3.3.1.min.js` ) and that worked

Replaced but still recieving the same issue
