### ISSUE TITLE
Using double click event for submission

### ISSUE THREAD

**Issue by grabby7** [fengyuanchen/jquery-cropper#10]
I want to let users submit a cropped image by double clicking the image (the crop modal). I've tried everything but I can't get jquery to read the double click event. I'm assuming its being overridden by the built-in double click event for toggleDragModeOnDblclick.

I have toggleDragModeOnDblclick:false,

I am trying:
`$( ".cropper-modal" ).dblclick(function() {
  alert( "Handler for .dblclick() called." );
});`

But I have tried #image and various other divs but can't get anything to fire.

**Comment by fengyuanchen** [comment]
Maybe you bind the event before the `.cropper-modal` is generated.

Try this:

```js
$('#myImage').on({
  ready: function () {
    $(".cropper-modal").dblclick(function () {
      alert("Handler for .dblclick() called.");
    });
  },
}).cropper(options);
```

**Comment by grabby7** [comment]
So that makes everything but the selection double-clickable. If you double click the background it runs the event, but the selection still overrides it. Thank you for the help though!

**Comment by fengyuanchen** [comment]
Maybe you can set both the `cropBoxResizable` and `cropBoxMovable` options to `false`.
