### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setDefaults' of undefined

### ISSUE THREAD

**Issue by hoolahoop** [fengyuanchen/jquery-cropper#11]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Chrome:
I get an error: Uncaught TypeError: Cannot read property 'setDefaults' of undefined, in jquery-cropper.js:68.
Firefox:
I get an error: TypeError: Cropper is undefined, in jquery-cropper,js:68:5

## Expected behavior

No error.

## Minimal reproduction of the problem with instructions

STEPS TO REPRODUCE

Copy/paste the following files into project: https://raw.githubusercontent.com/fengyuanchen/cropperjs/master/dist/cropper.js
https://raw.githubusercontent.com/fengyuanchen/cropperjs/master/dist/cropper.css
https://raw.githubusercontent.com/fengyuanchen/jquery-cropper/master/dist/jquery-cropper.js
https://raw.githubusercontent.com/fengyuanchen/jquery-cropper/master/dist/jquery-cropper.esm.js
https://raw.githubusercontent.com/fengyuanchen/jquery-cropper/master/dist/jquery-cropper.common.js

Add to html page:
head --
< link rel="stylesheet" type="text/css" href="/css/cropper.css">
body --
< script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
< script src="<?=$this->webroot;?>js/cropper.js"></script>
< script src="<?=$this->webroot;?>js/jquery-cropper.js"></script>

## What is the motivation / use case for changing the behavior?

Use cropper to crop an image that gets uploaded by a user, and then save the cropped image.

## Environment

<pre><code>
jquery-cropper version: 1.0.0

Browser:
- [x] Chrome (desktop) version 77.0.3865.90 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 69.0.2 (64-bit) (Firefox Quantum)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:
jquery-min version: 3.4.1
cropper version - 4.1.0
also tried cropper version - 1.5.6

</code></pre>

**Comment by fengyuanchen** [comment]
It seems you don't load the cropper.js on the page.

**Comment by hoolahoop** [comment]
Doesn't this line load cropper.js:
< script src="/js/cropper.js"></script>
?

I saved the file cropper.js on the server, and I see it being loaded in chrome inspector->network.

**Comment by fengyuanchen** [comment]
> https://github.com/fengyuanchen/jquery-cropper#installation

```html
<script src="/path/to/jquery.js"></script><!-- jQuery is required -->
<script src="/path/to/cropper.js"></script><!-- Cropper.js is required -->
<link  href="/path/to/cropper.css" rel="stylesheet">
<script src="/path/to/jquery-cropper.js"></script>
```
