### ISSUE TITLE
请问， 我这里截图出现了部分图片直接变成黑色的了，是什么原因导致的呢？

### ISSUE THREAD

**Issue by 544402029** [fengyuanchen/jquery-cropper#13]
![微信图片_20191106153252](https://user-images.githubusercontent.com/46950863/68281308-5cd71680-00b2-11ea-9125-893c00adde21.png)

**Comment by fengyuanchen** [comment]
图片太大，导致内存溢出了吧。建议限制图片大小，或者上传到服务端去裁剪。

**Comment by 544402029** [comment]
> 图片太大，导致内存溢出了吧。建议限制图片大小，或者上传到服务端去裁剪。

不应该啊  我这很多图片都是差不多大小的 ， 2m左右， 但是有的图片显示出来了， 有的图片直接黑了。 如果有的太大不是应该全部都黑吗？ 我这个现在的情况是很少有用户直接图片变黑， 而且这个用户裁剪的图片有的黑有的正常， 完全找不到问题在哪。。

**Comment by fengyuanchen** [comment]
建议禁用 `checkOrientation` 选项试试。

**Comment by 544402029** [comment]
> 建议局部`checkOrientation`选项试试。

问题找到了， 是图片放到极限大会出现这种情况。。

**Comment by fengyuanchen** [comment]
每放大一分，在最后裁切的时候都会增加一分内存。放太大真有可能超出内存限制，导致失效变黑。可以通过 `zoom` 事件控制允许放大的最大比率。

**Comment by 544402029** [comment]
> 每放大一分，在最后裁切的时候都会增加一分内存。放太大真有可能超出内存限制，导致失效变黑。可以通过 `zoom` 事件控制允许放大的最大比率。

非常感谢！
