### ISSUE TITLE
I set the preview option,but it does not show

### ISSUE THREAD

**Issue by Losunlee** [fengyuanchen/jquery-cropper#15]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## Current behavior

I set the preview option,but it does not show

## Environment

<pre><code>
jquery-cropper version: 1.0.1

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by fengyuanchen** [comment]
Please check if your provided value (selector or element) is valid.
