### ISSUE TITLE
Cropper is not a function

### ISSUE THREAD

**Issue by Zortaes** [fengyuanchen/jquery-cropper#17]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

On my symfony project with webpack encore, I am using PrestaImageBundle https://github.com/prestaconcept/PrestaImageBundle , I have installed cropper, as stated in the documentation https://github.com/fengyuanchen/jquery-cropper#installation but when uploading the image I ended up with this error in my console : 

cropper.js:158 Uncaught TypeError: this.$container.$preview.children(...).cropper is not a function
    at Cropper../vendor/presta/image-bundle/Resources/public/js/cropper.js.Cropper.prepareCropping (cropper.js:158)
    at FileReader.reader.onload (cropper.js:72)

There are no 404 error, only this one when uploading an image.

## Expected behavior

It should give me the option to crop the image to the desired size

## Minimal reproduction of the problem with instructions
But instead I end up with this error

## Environment

<pre><code>
jquery-cropper version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

here are links and config used : 

in base template
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> 

in twig config
 twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig'] 

in js file
 import 'jquery/dist/jquery.min';
import 'cropperjs/dist/cropper.min';
import 'jquery-cropper/dist/jquery-cropper.min.js';
import * as Cropper from '../../vendor/presta/image-bundle/Resources/public/js/cropper.js';
import '../css/form.scss'; 

in scss of my form
 @import "/../../node_modules/cropperjs/dist/cropper.min";
@import '../../vendor/presta/image-bundle/Resources/public/css/cropper.css'; 

If any of you has an idea why I end up with this error, please let me know, We have read documentation several times and still don't understand why it doesn't work.
</code></pre>

**Comment by IvanAddolorato** [comment]
@Zortaes did you get to resolve this issue? I'm getting the same error.
