### ISSUE TITLE
Elliptical crop in the jQuery version

### ISSUE THREAD

**Issue by Joshuajrodrigues** [fengyuanchen/jquery-cropper#24]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior

Currently I've seen some methods of getting the cropper view box to circular by changing the CSS. 

## Expected behavior

When I upload the image onto my server the image is still square or rectangular. I'm not really sure how to do the JavaScript, jQuery to get it to retain a circular crop

## Environment

<pre><code>
jquery-cropper version: 1.0.1 

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by fengyuanchen** [comment]
You can follow this example: https://fengyuanchen.github.io/cropperjs/examples/crop-a-round-image.html
