### ISSUE TITLE
Cropper is not moving smoothly, what could be possible reason for it

### ISSUE THREAD

**Issue by Mansiguptacsqt** [fengyuanchen/jquery-cropper#28]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
jquery-cropper version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by fengyuanchen** [comment]
Please fill out the template to provide more information.
