### ISSUE TITLE
with react-cropper , multiple selection

### ISSUE THREAD

**Issue by zergreen** [fengyuanchen/jquery-cropper#29]
sorry, this is not react-cropper but I heard it's implement from this repo.
is someone know how to implement  multiple selection in react-cropper .

[react-cropper](https://www.npmjs.com/package/react-cropper)

<img width="1192" alt="Screenshot 2567-04-24 at 01 25 39" src="https://github.com/fengyuanchen/jquery-cropper/assets/68957232/cf49cb3a-93ef-48e4-87cd-1f313e418a87">

**Comment by fengyuanchen** [comment]
Just use Cropper.js 2.0 directly.

**Comment by zergreen** [comment]
> Just use Cropper.js 2.0 directly.

ok, it's has only way T o T. I will try to make new implement sir.
