### ISSUE TITLE
Read image bug

### ISSUE THREAD

**Issue by nim** [fengyuanchen/jquery-cropper#6]
hi,

When I tested all the features of croper. I encountered an exception when opening images. Exceptions appear only if these options are enabled:
                 rotatable: false,
                 scalable: false,

I have attached one of these images. You can repeat this error. Use your demo page https://fengyuanchen.github.io/jquery-cropper/

![13](https://user-images.githubusercontent.com/41398/46878467-0f0ac300-ce4c-11e8-841b-5a4d4cfa4d03.jpg)

0x800a13e1 - JavaScript Runtime Error: DataView is trying to access data outside the specified buffer length

![default](https://user-images.githubusercontent.com/41398/46878822-eafbb180-ce4c-11e8-9f71-57ba6b55d223.png)

**Comment by fengyuanchen** [comment]
You may have to set the `checkOrientation` option to `false` as your image does not have valid Exif information.

**Comment by fengyuanchen** [comment]
I have fixed this by ignoring range error: https://github.com/fengyuanchen/cropperjs/commit/2ca48d44569eeac2d11887eef30c53a3110829e6
