### ISSUE TITLE
question with ie9

### ISSUE THREAD

**Issue by mabidenengma** [fengyuanchen/jquery-cropper#8]
I found that after component initialization in ie9, I wrote "SCRIPT5022: script block raised exception but not caught (1895) (1,13098)".The picture is loaded, but the cropping box is not loaded. Is there any problem?
![3cd734a3cebc2317437c38aeb149d23](https://user-images.githubusercontent.com/22976428/61025700-0a2b6d80-a3e4-11e9-9c9c-804e0afa2661.png)
![39cdb13fba79d611b1fae5a705aaa51](https://user-images.githubusercontent.com/22976428/61025704-0bf53100-a3e4-11e9-8244-4161df048a78.png)

**Comment by fengyuanchen** [comment]
Did you include the `cropper.css` file?

**Comment by Owohlet** [comment]
Hi I want to use jquery-cropper in a rails application, I was wondering if there is a CDN with the proper versions vis-a-vis the specific version of jquery it works with. I have tried to get from cdnjs and it doesn't seem to be working.

**Comment by fengyuanchen** [comment]
@mabidenengma Try the latest version of Cropper.js or set the `checkOrientation` option to `false`.

**Comment by fengyuanchen** [comment]
@Owohlet 

```html
<script src="https://unpkg.com/jquery@3.4.1/dist/jquery.min.js"></script>
<script src="https://unpkg.com/cropperjs@1.5.5/dist/cropper.min.js"></script>
<script src="https://unpkg.com/jquery-cropper@1.0.0/dist/jquery-cropper.min.js"></script>
```
